#!/bin/bash

timeout=30

echo "priority,bogo_ops,cpu_used" > sched-prio_res
echo "priority,usr,sys,iowait" > sched-prio_cpu_res

for ((i=1; i<100; i=i+5))
do
    echo $i

    sudo mpstat 1 $timeout | grep "all" | sed "s/,/\./g" | awk --assign=cpu="$i" '{printf cpu","$3","$5","$6"\n"}' >> sched-prio_cpu_res &

    sudo stress-ng --cpu 10 --sched rr --sched-prio $i --metrics --timeout $timeout |
	awk --assign=cpu="$i" '{printf cpu","$5","$11"\n"}' | head --lines=-5 | tail --lines=+6 >> sched-prio_res
done
